server:
  port: 8080
  servlet:
    context-path: /

spring-doc:
  swagger-ui:
    path: /docs

spring:
  application:
    name: backend-challenge

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/challenge_tech_bd
    username: postgres
    password: postgres

  sql:
    init:
      mode: always

logging:
  level:
    org.springframework.web: DEBUG
    com.your.package: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,beans,env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true